export const CONTAS_PADRAO_CFC = [
  // GRUPO 1 - ATIVO
  { codigo: '1', nome: 'ATIVO', tipo: 'Sintética', natureza: 'Devedora', nivel: 1, grupo: 'ATIVO', codigoPai: null },
  { codigo: '1.1', nome: 'ATIVO CIRCULANTE', tipo: 'Sintética', natureza: 'Devedora', nivel: 2, grupo: 'ATIVO', codigoPai: '1' },
  { codigo: '1.1.1', nome: 'Caixa e Equivalentes de Caixa', tipo: 'Sintética', natureza: 'Devedora', nivel: 3, grupo: 'ATIVO', codigoPai: '1.1' },
  { codigo: '1.1.1.01', nome: 'Caixa', tipo: 'Sintética', natureza: 'Devedora', nivel: 4, grupo: 'ATIVO', codigoPai: '1.1.1' },
  { codigo: '1.1.1.01.001', nome: 'Caixa Geral', tipo: 'Analítica', natureza: 'Devedora', nivel: 5, grupo: 'ATIVO', codigoPai: '1.1.1.01' },
  { codigo: '1.1.1.02', nome: 'Bancos Conta Movimento', tipo: 'Sintética', natureza: 'Devedora', nivel: 4, grupo: 'ATIVO', codigoPai: '1.1.1' },
  { codigo: '1.1.1.02.001', nome: 'Banco do Brasil', tipo: 'Analítica', natureza: 'Devedora', nivel: 5, grupo: 'ATIVO', codigoPai: '1.1.1.02' },
  { codigo: '1.1.1.02.002', nome: 'Itaú', tipo: 'Analítica', natureza: 'Devedora', nivel: 5, grupo: 'ATIVO', codigoPai: '1.1.1.02' },
  { codigo: '1.1.1.03', nome: 'Aplicações Financeiras', tipo: 'Sintética', natureza: 'Devedora', nivel: 4, grupo: 'ATIVO', codigoPai: '1.1.1' },
  { codigo: '1.1.1.03.001', nome: 'Aplicações de Liquidez Imediata', tipo: 'Analítica', natureza: 'Devedora', nivel: 5, grupo: 'ATIVO', codigoPai: '1.1.1.03' },
  { codigo: '1.1.2', nome: 'Clientes e Contas a Receber', tipo: 'Sintética', natureza: 'Devedora', nivel: 3, grupo: 'ATIVO', codigoPai: '1.1' },
  { codigo: '1.1.2.01', nome: 'Duplicatas a Receber', tipo: 'Analítica', natureza: 'Devedora', nivel: 4, grupo: 'ATIVO', codigoPai: '1.1.2' },
  { codigo: '1.1.2.02', nome: '(-) Provisão p/ Devedores Duvidosos', tipo: 'Analítica', natureza: 'Devedora', nivel: 4, grupo: 'ATIVO', codigoPai: '1.1.2' },
  { codigo: '1.1.3', nome: 'Estoques', tipo: 'Sintética', natureza: 'Devedora', nivel: 3, grupo: 'ATIVO', codigoPai: '1.1' },
  { codigo: '1.1.3.01', nome: 'Mercadorias para Revenda', tipo: 'Analítica', natureza: 'Devedora', nivel: 4, grupo: 'ATIVO', codigoPai: '1.1.3' },
  { codigo: '1.1.3.02', nome: 'Matérias-Primas', tipo: 'Analítica', natureza: 'Devedora', nivel: 4, grupo: 'ATIVO', codigoPai: '1.1.3' },
  { codigo: '1.1.4', nome: 'Impostos a Recuperar', tipo: 'Sintética', natureza: 'Devedora', nivel: 3, grupo: 'ATIVO', codigoPai: '1.1' },
  { codigo: '1.1.4.01', nome: 'ICMS a Recuperar', tipo: 'Analítica', natureza: 'Devedora', nivel: 4, grupo: 'ATIVO', codigoPai: '1.1.4' },
  { codigo: '1.1.4.02', nome: 'PIS a Recuperar', tipo: 'Analítica', natureza: 'Devedora', nivel: 4, grupo: 'ATIVO', codigoPai: '1.1.4' },
  { codigo: '1.1.4.03', nome: 'COFINS a Recuperar', tipo: 'Analítica', natureza: 'Devedora', nivel: 4, grupo: 'ATIVO', codigoPai: '1.1.4' },
  { codigo: '1.1.5', nome: 'Despesas Antecipadas', tipo: 'Sintética', natureza: 'Devedora', nivel: 3, grupo: 'ATIVO', codigoPai: '1.1' },
  { codigo: '1.1.5.01', nome: 'Seguros a Apropriar', tipo: 'Analítica', natureza: 'Devedora', nivel: 4, grupo: 'ATIVO', codigoPai: '1.1.5' },
  { codigo: '1.2', nome: 'ATIVO NÃO CIRCULANTE', tipo: 'Sintética', natureza: 'Devedora', nivel: 2, grupo: 'ATIVO', codigoPai: '1' },
  { codigo: '1.2.1', nome: 'Realizável a Longo Prazo', tipo: 'Sintética', natureza: 'Devedora', nivel: 3, grupo: 'ATIVO', codigoPai: '1.2' },
  { codigo: '1.2.1.01', nome: 'Depósitos Judiciais', tipo: 'Analítica', natureza: 'Devedora', nivel: 4, grupo: 'ATIVO', codigoPai: '1.2.1' },
  { codigo: '1.2.2', nome: 'Investimentos', tipo: 'Sintética', natureza: 'Devedora', nivel: 3, grupo: 'ATIVO', codigoPai: '1.2' },
  { codigo: '1.2.2.01', nome: 'Participações Societárias', tipo: 'Analítica', natureza: 'Devedora', nivel: 4, grupo: 'ATIVO', codigoPai: '1.2.2' },
  { codigo: '1.2.3', nome: 'Imobilizado', tipo: 'Sintética', natureza: 'Devedora', nivel: 3, grupo: 'ATIVO', codigoPai: '1.2' },
  { codigo: '1.2.3.01', nome: 'Imóveis', tipo: 'Analítica', natureza: 'Devedora', nivel: 4, grupo: 'ATIVO', codigoPai: '1.2.3' },
  { codigo: '1.2.3.02', nome: 'Veículos', tipo: 'Analítica', natureza: 'Devedora', nivel: 4, grupo: 'ATIVO', codigoPai: '1.2.3' },
  { codigo: '1.2.3.03', nome: 'Máquinas e Equipamentos', tipo: 'Analítica', natureza: 'Devedora', nivel: 4, grupo: 'ATIVO', codigoPai: '1.2.3' },
  { codigo: '1.2.3.04', nome: 'Móveis e Utensílios', tipo: 'Analítica', natureza: 'Devedora', nivel: 4, grupo: 'ATIVO', codigoPai: '1.2.3' },
  { codigo: '1.2.3.05', nome: 'Computadores e Periféricos', tipo: 'Analítica', natureza: 'Devedora', nivel: 4, grupo: 'ATIVO', codigoPai: '1.2.3' },
  { codigo: '1.2.3.90', nome: '(-) Depreciação Acumulada', tipo: 'Analítica', natureza: 'Devedora', nivel: 4, grupo: 'ATIVO', codigoPai: '1.2.3' },
  { codigo: '1.2.4', nome: 'Intangível', tipo: 'Sintética', natureza: 'Devedora', nivel: 3, grupo: 'ATIVO', codigoPai: '1.2' },
  { codigo: '1.2.4.01', nome: 'Softwares', tipo: 'Analítica', natureza: 'Devedora', nivel: 4, grupo: 'ATIVO', codigoPai: '1.2.4' },
  { codigo: '1.2.4.02', nome: 'Marcas e Patentes', tipo: 'Analítica', natureza: 'Devedora', nivel: 4, grupo: 'ATIVO', codigoPai: '1.2.4' },
  { codigo: '1.2.4.90', nome: '(-) Amortização Acumulada', tipo: 'Analítica', natureza: 'Devedora', nivel: 4, grupo: 'ATIVO', codigoPai: '1.2.4' },

  // GRUPO 2 - PASSIVO
  { codigo: '2', nome: 'PASSIVO', tipo: 'Sintética', natureza: 'Credora', nivel: 1, grupo: 'PASSIVO', codigoPai: null },
  { codigo: '2.1', nome: 'PASSIVO CIRCULANTE', tipo: 'Sintética', natureza: 'Credora', nivel: 2, grupo: 'PASSIVO', codigoPai: '2' },
  { codigo: '2.1.1', nome: 'Fornecedores', tipo: 'Sintética', natureza: 'Credora', nivel: 3, grupo: 'PASSIVO', codigoPai: '2.1' },
  { codigo: '2.1.1.01', nome: 'Fornecedores Nacionais', tipo: 'Analítica', natureza: 'Credora', nivel: 4, grupo: 'PASSIVO', codigoPai: '2.1.1' },
  { codigo: '2.1.1.02', nome: 'Fornecedores Estrangeiros', tipo: 'Analítica', natureza: 'Credora', nivel: 4, grupo: 'PASSIVO', codigoPai: '2.1.1' },
  { codigo: '2.1.2', nome: 'Obrigações Trabalhistas', tipo: 'Sintética', natureza: 'Credora', nivel: 3, grupo: 'PASSIVO', codigoPai: '2.1' },
  { codigo: '2.1.2.01', nome: 'Salários a Pagar', tipo: 'Analítica', natureza: 'Credora', nivel: 4, grupo: 'PASSIVO', codigoPai: '2.1.2' },
  { codigo: '2.1.2.02', nome: 'FGTS a Recolher', tipo: 'Analítica', natureza: 'Credora', nivel: 4, grupo: 'PASSIVO', codigoPai: '2.1.2' },
  { codigo: '2.1.2.03', nome: 'INSS a Recolher', tipo: 'Analítica', natureza: 'Credora', nivel: 4, grupo: 'PASSIVO', codigoPai: '2.1.2' },
  { codigo: '2.1.2.04', nome: 'IRRF a Recolher', tipo: 'Analítica', natureza: 'Credora', nivel: 4, grupo: 'PASSIVO', codigoPai: '2.1.2' },
  { codigo: '2.1.3', nome: 'Obrigações Tributárias', tipo: 'Sintética', natureza: 'Credora', nivel: 3, grupo: 'PASSIVO', codigoPai: '2.1' },
  { codigo: '2.1.3.01', nome: 'ICMS a Recolher', tipo: 'Analítica', natureza: 'Credora', nivel: 4, grupo: 'PASSIVO', codigoPai: '2.1.3' },
  { codigo: '2.1.3.02', nome: 'PIS a Recolher', tipo: 'Analítica', natureza: 'Credora', nivel: 4, grupo: 'PASSIVO', codigoPai: '2.1.3' },
  { codigo: '2.1.3.03', nome: 'COFINS a Recolher', tipo: 'Analítica', natureza: 'Credora', nivel: 4, grupo: 'PASSIVO', codigoPai: '2.1.3' },
  { codigo: '2.1.3.04', nome: 'ISS a Recolher', tipo: 'Analítica', natureza: 'Credora', nivel: 4, grupo: 'PASSIVO', codigoPai: '2.1.3' },
  { codigo: '2.1.3.05', nome: 'IRPJ a Recolher', tipo: 'Analítica', natureza: 'Credora', nivel: 4, grupo: 'PASSIVO', codigoPai: '2.1.3' },
  { codigo: '2.1.3.06', nome: 'CSLL a Recolher', tipo: 'Analítica', natureza: 'Credora', nivel: 4, grupo: 'PASSIVO', codigoPai: '2.1.3' },
  { codigo: '2.1.4', nome: 'Empréstimos e Financiamentos CP', tipo: 'Sintética', natureza: 'Credora', nivel: 3, grupo: 'PASSIVO', codigoPai: '2.1' },
  { codigo: '2.1.4.01', nome: 'Empréstimos Bancários', tipo: 'Analítica', natureza: 'Credora', nivel: 4, grupo: 'PASSIVO', codigoPai: '2.1.4' },
  { codigo: '2.2', nome: 'PASSIVO NÃO CIRCULANTE', tipo: 'Sintética', natureza: 'Credora', nivel: 2, grupo: 'PASSIVO', codigoPai: '2' },
  { codigo: '2.2.1', nome: 'Empréstimos e Financiamentos LP', tipo: 'Sintética', natureza: 'Credora', nivel: 3, grupo: 'PASSIVO', codigoPai: '2.2' },
  { codigo: '2.2.1.01', nome: 'Financiamentos Bancários LP', tipo: 'Analítica', natureza: 'Credora', nivel: 4, grupo: 'PASSIVO', codigoPai: '2.2.1' },
  { codigo: '2.2.2', nome: 'Provisões', tipo: 'Sintética', natureza: 'Credora', nivel: 3, grupo: 'PASSIVO', codigoPai: '2.2' },
  { codigo: '2.2.2.01', nome: 'Provisão p/ Contingências', tipo: 'Analítica', natureza: 'Credora', nivel: 4, grupo: 'PASSIVO', codigoPai: '2.2.2' },

  // GRUPO 3 - PATRIMÔNIO LÍQUIDO
  { codigo: '3', nome: 'PATRIMÔNIO LÍQUIDO', tipo: 'Sintética', natureza: 'Credora', nivel: 1, grupo: 'PL', codigoPai: null },
  { codigo: '3.1', nome: 'Capital Social', tipo: 'Sintética', natureza: 'Credora', nivel: 2, grupo: 'PL', codigoPai: '3' },
  { codigo: '3.1.1', nome: 'Capital Social Subscrito', tipo: 'Analítica', natureza: 'Credora', nivel: 3, grupo: 'PL', codigoPai: '3.1' },
  { codigo: '3.1.2', nome: '(-) Capital a Integralizar', tipo: 'Analítica', natureza: 'Devedora', nivel: 3, grupo: 'PL', codigoPai: '3.1' },
  { codigo: '3.2', nome: 'Reservas de Capital', tipo: 'Sintética', natureza: 'Credora', nivel: 2, grupo: 'PL', codigoPai: '3' },
  { codigo: '3.2.1', nome: 'Ágio na Emissão de Ações', tipo: 'Analítica', natureza: 'Credora', nivel: 3, grupo: 'PL', codigoPai: '3.2' },
  { codigo: '3.3', nome: 'Reservas de Lucros', tipo: 'Sintética', natureza: 'Credora', nivel: 2, grupo: 'PL', codigoPai: '3' },
  { codigo: '3.3.1', nome: 'Reserva Legal', tipo: 'Analítica', natureza: 'Credora', nivel: 3, grupo: 'PL', codigoPai: '3.3' },
  { codigo: '3.3.2', nome: 'Reserva Estatutária', tipo: 'Analítica', natureza: 'Credora', nivel: 3, grupo: 'PL', codigoPai: '3.3' },
  { codigo: '3.4', nome: 'Lucros/Prejuízos Acumulados', tipo: 'Sintética', natureza: 'Credora', nivel: 2, grupo: 'PL', codigoPai: '3' },
  { codigo: '3.4.1', nome: 'Lucros Acumulados', tipo: 'Analítica', natureza: 'Credora', nivel: 3, grupo: 'PL', codigoPai: '3.4' },
  { codigo: '3.4.2', nome: '(-) Prejuízos Acumulados', tipo: 'Analítica', natureza: 'Devedora', nivel: 3, grupo: 'PL', codigoPai: '3.4' },

  // GRUPO 4 - RECEITAS
  { codigo: '4', nome: 'RECEITAS', tipo: 'Sintética', natureza: 'Credora', nivel: 1, grupo: 'RECEITA', codigoPai: null },
  { codigo: '4.1', nome: 'Receita Operacional Bruta', tipo: 'Sintética', natureza: 'Credora', nivel: 2, grupo: 'RECEITA', codigoPai: '4' },
  { codigo: '4.1.1', nome: 'Receita de Vendas de Mercadorias', tipo: 'Analítica', natureza: 'Credora', nivel: 3, grupo: 'RECEITA', codigoPai: '4.1' },
  { codigo: '4.1.2', nome: 'Receita de Prestação de Serviços', tipo: 'Analítica', natureza: 'Credora', nivel: 3, grupo: 'RECEITA', codigoPai: '4.1' },
  { codigo: '4.2', nome: '(-) Deduções da Receita', tipo: 'Sintética', natureza: 'Devedora', nivel: 2, grupo: 'RECEITA', codigoPai: '4' },
  { codigo: '4.2.1', nome: '(-) Devoluções de Vendas', tipo: 'Analítica', natureza: 'Devedora', nivel: 3, grupo: 'RECEITA', codigoPai: '4.2' },
  { codigo: '4.2.2', nome: '(-) Descontos Incondicionais', tipo: 'Analítica', natureza: 'Devedora', nivel: 3, grupo: 'RECEITA', codigoPai: '4.2' },
  { codigo: '4.2.3', nome: '(-) ICMS s/ Vendas', tipo: 'Analítica', natureza: 'Devedora', nivel: 3, grupo: 'RECEITA', codigoPai: '4.2' },
  { codigo: '4.2.4', nome: '(-) PIS s/ Faturamento', tipo: 'Analítica', natureza: 'Devedora', nivel: 3, grupo: 'RECEITA', codigoPai: '4.2' },
  { codigo: '4.2.5', nome: '(-) COFINS s/ Faturamento', tipo: 'Analítica', natureza: 'Devedora', nivel: 3, grupo: 'RECEITA', codigoPai: '4.2' },
  { codigo: '4.2.6', nome: '(-) ISS s/ Serviços', tipo: 'Analítica', natureza: 'Devedora', nivel: 3, grupo: 'RECEITA', codigoPai: '4.2' },
  { codigo: '4.3', nome: 'Receitas Financeiras', tipo: 'Sintética', natureza: 'Credora', nivel: 2, grupo: 'RECEITA', codigoPai: '4' },
  { codigo: '4.3.1', nome: 'Juros Ativos', tipo: 'Analítica', natureza: 'Credora', nivel: 3, grupo: 'RECEITA', codigoPai: '4.3' },
  { codigo: '4.3.2', nome: 'Rendimentos de Aplicações', tipo: 'Analítica', natureza: 'Credora', nivel: 3, grupo: 'RECEITA', codigoPai: '4.3' },

  // GRUPO 5 - CUSTOS E DESPESAS
  { codigo: '5', nome: 'CUSTOS E DESPESAS', tipo: 'Sintética', natureza: 'Devedora', nivel: 1, grupo: 'DESPESA', codigoPai: null },
  { codigo: '5.1', nome: 'Custo das Mercadorias Vendidas (CMV)', tipo: 'Sintética', natureza: 'Devedora', nivel: 2, grupo: 'DESPESA', codigoPai: '5' },
  { codigo: '5.1.1', nome: 'CMV — Mercadorias', tipo: 'Analítica', natureza: 'Devedora', nivel: 3, grupo: 'DESPESA', codigoPai: '5.1' },
  { codigo: '5.2', nome: 'Despesas Operacionais', tipo: 'Sintética', natureza: 'Devedora', nivel: 2, grupo: 'DESPESA', codigoPai: '5' },
  { codigo: '5.2.1', nome: 'Despesas com Pessoal', tipo: 'Sintética', natureza: 'Devedora', nivel: 3, grupo: 'DESPESA', codigoPai: '5.2' },
  { codigo: '5.2.1.01', nome: 'Salários e Ordenados', tipo: 'Analítica', natureza: 'Devedora', nivel: 4, grupo: 'DESPESA', codigoPai: '5.2.1' },
  { codigo: '5.2.1.02', nome: 'Férias', tipo: 'Analítica', natureza: 'Devedora', nivel: 4, grupo: 'DESPESA', codigoPai: '5.2.1' },
  { codigo: '5.2.1.03', nome: '13º Salário', tipo: 'Analítica', natureza: 'Devedora', nivel: 4, grupo: 'DESPESA', codigoPai: '5.2.1' },
  { codigo: '5.2.1.04', nome: 'FGTS', tipo: 'Analítica', natureza: 'Devedora', nivel: 4, grupo: 'DESPESA', codigoPai: '5.2.1' },
  { codigo: '5.2.1.05', nome: 'INSS Patronal', tipo: 'Analítica', natureza: 'Devedora', nivel: 4, grupo: 'DESPESA', codigoPai: '5.2.1' },
  { codigo: '5.2.2', nome: 'Despesas Administrativas', tipo: 'Sintética', natureza: 'Devedora', nivel: 3, grupo: 'DESPESA', codigoPai: '5.2' },
  { codigo: '5.2.2.01', nome: 'Aluguel', tipo: 'Analítica', natureza: 'Devedora', nivel: 4, grupo: 'DESPESA', codigoPai: '5.2.2' },
  { codigo: '5.2.2.02', nome: 'Energia Elétrica', tipo: 'Analítica', natureza: 'Devedora', nivel: 4, grupo: 'DESPESA', codigoPai: '5.2.2' },
  { codigo: '5.2.2.03', nome: 'Água e Esgoto', tipo: 'Analítica', natureza: 'Devedora', nivel: 4, grupo: 'DESPESA', codigoPai: '5.2.2' },
  { codigo: '5.2.2.04', nome: 'Telefone e Internet', tipo: 'Analítica', natureza: 'Devedora', nivel: 4, grupo: 'DESPESA', codigoPai: '5.2.2' },
  { codigo: '5.2.2.05', nome: 'Material de Escritório', tipo: 'Analítica', natureza: 'Devedora', nivel: 4, grupo: 'DESPESA', codigoPai: '5.2.2' },
  { codigo: '5.2.2.06', nome: 'Depreciação', tipo: 'Analítica', natureza: 'Devedora', nivel: 4, grupo: 'DESPESA', codigoPai: '5.2.2' },
  { codigo: '5.2.3', nome: 'Despesas Financeiras', tipo: 'Sintética', natureza: 'Devedora', nivel: 3, grupo: 'DESPESA', codigoPai: '5.2' },
  { codigo: '5.2.3.01', nome: 'Juros Passivos', tipo: 'Analítica', natureza: 'Devedora', nivel: 4, grupo: 'DESPESA', codigoPai: '5.2.3' },
  { codigo: '5.2.3.02', nome: 'Tarifas Bancárias', tipo: 'Analítica', natureza: 'Devedora', nivel: 4, grupo: 'DESPESA', codigoPai: '5.2.3' },
  { codigo: '5.2.3.03', nome: 'IOF', tipo: 'Analítica', natureza: 'Devedora', nivel: 4, grupo: 'DESPESA', codigoPai: '5.2.3' },
];

export async function criarPlanoContasParaEmpresa(tx, empresaId) {
  const codigoParaId = new Map();
  for (const c of CONTAS_PADRAO_CFC) {
    const contaPaiId = c.codigoPai ? codigoParaId.get(c.codigoPai) : null;
    const conta = await tx.conta.create({
      data: {
        codigo: c.codigo,
        nome: c.nome,
        tipo: c.tipo,
        natureza: c.natureza,
        nivel: c.nivel,
        grupo: c.grupo,
        contaPaiId,
        empresaId,
      },
    });
    codigoParaId.set(c.codigo, conta.id);
  }
}
